### ISSUE TITLE
Linspace from 0 to 1

### ISSUE THREAD

**Issue by xinge008** [DuaneNielsen/keypoints#2]
Hi, nice work, 

I am wondering why the range of linspace (prob2keypoint function) is from 0 to 1, while in the official implementation, it is from -1 to 1.

**Comment by DuaneNielsen** [comment]
Thanks.

It's just an implementation choice.  I prefer to think in probabilities only, and to have image co-ordinate space be (0,1) rather than (-1,1).

Theoretically its better to be -1 .. 1, because you get the full representative range, without the chance of gradients getting out of range, but I prefer not to bother with that.
